### ISSUE TITLE
Viewing Denjuu status screen or Field Guide in SGB mode causes screen to flash yellow

### ISSUE THREAD

**Issue by Blaziken257** [telefang/telefang#179]
In Super Game Boy mode, when viewing the Denjuu status screen (either from selecting Contacts or viewing an enemy Denjuu status), or the Field Guide, the entire screen is filled with a yellow flash while either screen is loading. This flash is unpleasant on the eyes and could cause problems for people with sensitive eyesight.

This can be reproduced in BGB (in SGB mode) and on real SGB hardware.

## Additional information

Both of these screens appear to set the palette via the PAL01 and PAL23 commands, unlike the rest of the game, which uses PAL_SET to select a palette previously initialized by PAL_TRN and ATTR_TRN.

### Contacts screen

When the contacts screen loads in SGB mode, the following packets are sent (observed via BGB's SGB packets window):

```
1 00 PAL01    01.FF.03.FF 7F.B5.56.A5 14.DF.03.9F 02.35.02.00
1 01 PAL23    09.FF.7F.F9 6F.8C.3B.A0 08.FF.5B.3F 2A.08.00.00
```

The first command sets the SGB's background palette to 03FF, which is yellow, and the second command (which immediately follows the first) sets the SGB's background to 7FFF, which is white. The different colors in these two commands are what causes the flashing on the screen. Why is the first command setting the background to yellow in the first place?

### Field Guide

When the Field Guide is loaded in SGB mode, these packets are sent:

```
1 00 PAL01    01.7F.1F.FF 7F.B5.56.A5 14.BD.77.7F 47.00.00.00
1 01 PAL23    09.FF.7F.F9 6F.8C.3B.A0 08.FF.5B.3F 2A.08.00.00
```

The situation is similar in that the SGB's background color is first set to 1F7F (a washed-out yellow), and then to 7FFF (white). Again, does it break anything to set it to white in the first command?

**Comment by kmeisthax** [comment]
The reason why we write yellow before white is because we're pulling from CGB colors and this screen was not designed with the limitations of the Super Famicom PPU in mind. We pull what the game has staged for CGB colors and convert it into SGB colorspace and upload that with a PALxy command. (The instances of PAL_SET commands are for screens where I had hand-converted colors to SGB mode. We plan to use PALxy commands going forward.) It wouldn't be too difficult to alter the conversion function to never change color zero, which would remove the flash and prevent us from making entirely broken screens.

**Comment by kmeisthax** [comment]
I believe 88874db95ce0d2b5c36d7558528bdc130639f332 resolves this issue; it forces color zero to always be written as white.
