### ISSUE TITLE
Field Guide entries have several text issues

### ISSUE THREAD

**Issue by Blaziken257** [telefang/telefang#315]
Many Field Guide entries have various text issues. These include:

- Two line breaks instead of one, which results in blank lines (see Monstera's and unknown entries)
- Some lines are unnecessarily short (see Telopea's entry)
- Part of one line can overlap and replace another line (see Lapeirousia's entry)

![bgb00577](https://user-images.githubusercontent.com/2187686/60392340-3cb89a80-9ab5-11e9-99d6-51dc3f868def.png)![bgb00578](https://user-images.githubusercontent.com/2187686/60392339-3c200400-9ab5-11e9-8477-f45625bfe372.png)
![bgb00571](https://user-images.githubusercontent.com/2187686/60392342-493cf300-9ab5-11e9-8342-5c83fbe9fd9c.png)![bgb00572](https://user-images.githubusercontent.com/2187686/60392343-493cf300-9ab5-11e9-8c36-a3959c8e77ae.png)
![bgb00579](https://user-images.githubusercontent.com/2187686/60392345-5528b500-9ab5-11e9-80b8-75d8d266108d.png)![bgb00580](https://user-images.githubusercontent.com/2187686/60392346-5528b500-9ab5-11e9-9ae3-fccb9af2e951.png)
![bgb00570](https://user-images.githubusercontent.com/2187686/60392350-65d92b00-9ab5-11e9-9753-2eda2112440e.png)

**Comment by Blaziken257** [comment]
I've noticed that advancing the text with A around 42 or so times causes further glitches, similar to Lapeirousia's entry.

**Comment by obskyr** [comment]
Some of these issues (albeit perhaps not the A button one) are due to the switch from automatic to manual formatting. As it stands, I've wrapped all the text manually, but it's still being run through the auto-wrapper upon insertion – and wrapping twice does not a well-wrapped string make. When the auto-formatter is turned off for already formatted lines, many of these issues will go away.
