### ISSUE TITLE
Several actions in shops are laggy on SGB

### ISSUE THREAD

**Issue by Blaziken257** [telefang/telefang#340]
When playing on an SGB, while in a shop, several actions are laggy, such as picking up items, or purchasing them at the counter. This is because every time a textbox is drawn, a ATTR_BLK packet is sent, which is supposed to give a textbox its proper palette. However, the way this is implemented is inefficient: even if the text box is already present and simply needs to change the text without having to update the color palette, an ATTR_BLK packet is still sent. Sending packets to the SGB causes a bit of a delay, and whenever you get close to another item, two of these packets are sent. When actually buying the items at the counter, more ATTR_BLK packets are sent, one for each item (up to four). All of this makes buying items noticeably slower on the SGB than on the GBC. While some lag is inevitable on the SGB, ATTR_BLK packets should ideally only be sent when necessary, i.e. if a text box appears or disappears.

An animated GIF is shown below. Notice the delays every time the player moves next to an item, or purchases them at the counter.

![Telefang_SGB_shop_slowness](https://user-images.githubusercontent.com/2187686/61598261-b97bf780-abcf-11e9-8f87-7c0c36b8ce39.gif)

A similar (possibly related) issue exists when a Denjuu recovers HP on the overworld while another NPC is running: Each time the Denjuu gains an HP, the NPC stops for a moment, shown below.

![Telefang_SGB_textbox_slowness](https://user-images.githubusercontent.com/2187686/61598457-25ac2a80-abd3-11e9-8649-c8302a482146.gif)

**Comment by andwhyisit** [comment]
Alright I probably should explain why this issue is still open. All of the lag was fixed except for one place: when you walk away from the top counter the top-right window is closed, and the resulting ATTR_BLK packet sent creates a notable lag in the player's walking animation. There are no inefficiencies with packet sending here, its just that the moment the window closes is rather unfortunate.

The only solution would be to change the behaviour of the top-right window in SGB mode so that it closes at a time when the player isn't moving.
