### ISSUE TITLE
Failed to open overlay file baseroms/baserom_pw.gbc

### ISSUE THREAD

**Issue by IoIxDButStronger** [telefang/telefang#369]
I attempted to compile the code raw, with no changes made, and I got this:

https://pastebin.com/raw/vgWpdpNz

I tried downloading the roms online and renaming them, but i got the same results

**Comment by IoIxDButStronger** [comment]
I reread the README and I have badly dumped roms. Where can I get dumped roms that DO work?

**Comment by obskyr** [comment]
Sorry, it'd be bad form link you to them here. Look around a bit and I'm sure you'll succeed eventually. Make sure to use `md5sum` or a similar tool to confirm that your ROMs were dumped correctly.

I'll close this issue since you identified the problem, but feel free to keep commenting here and we'll reply.
